### ISSUE TITLE
Issue with starting app

### ISSUE THREAD

**Issue by bigbadbrad** [manikandanraji/youtubeclone-frontend#15] opened 2021-01-14 00:49 UTC
When you first open up the server and then client, are you supposed to signup initially?  I get the following error when I try to sign up - attached.
<img width="1432" alt="Screen Shot 2021-01-13 at 4 42 47 PM" src="https://user-images.githubusercontent.com/1226677/104529558-e475ba80-55be-11eb-9d81-c13a3d466d4f.png">

I put an .env in the frontend root:
REACT_APP_BACKEND_URL="http://localhost:5000/api/v1/"
REACT_APP_CLOUDINARY_ENDPOINT="https://api.cloudinary.com/v1_1/funniestpets"

I put an .env in the backend root:
JWT_SECRET="I love shrimp with mayonnaise"
JWT_EXPIRE=30d // or any reasonable value that you prefer
DATABASE_URL="postgres://postgres:password@localhost:6432/dev?sslmode=disable"

Also your demo doesn't work either.  When I try to sign up, it doesn't do anything.

**Comment by manikandanraji** [comment] 2021-01-14 05:50
in the console, you can see the "POST" request is being made to the endpoint 'http://localhost:3000/undefined/auth/signup'. That's the issue. Make sure to you edit your env variables. If you make any changes to your .env file, you need to restart the react dev server. 

You can now try the demo app, fixed the issue.

**Comment by bigbadbrad** [comment] 2021-01-14 19:49
Hi I tried that and it doesn't work.  When I start up the backend, it appears that it runs off http://localhost:5000
Therefore, is my env. for frontend and backend posted above correct?

**Comment by manikandanraji** [comment] 2021-01-15 02:54
I think the issue is in my part. I forgot to update the README section. The .env file for the frontend should look like this:

![carbon](https://user-images.githubusercontent.com/34580944/104675181-f6647400-570a-11eb-8a30-8f8cbf483962.png)

**Comment by bigbadbrad** [comment] 2021-01-15 03:28
That's what I have in the client .env file
<img width="873" alt="Screen Shot 2021-01-14 at 7 25 43 PM" src="https://user-images.githubusercontent.com/1226677/104677627-96d07f00-569e-11eb-955e-338ce7e5f4f6.png">

and still have the same problem
<img width="1424" alt="Screen Shot 2021-01-14 at 7 25 30 PM" src="https://user-images.githubusercontent.com/1226677/104677679-af409980-569e-11eb-8b81-226b393aee3b.png">

**Comment by bigbadbrad** [comment] 2021-01-15 03:36
I see your fix.  That fixed the POST but now I have another problem.

<img width="1427" alt="Screen Shot 2021-01-14 at 7 35 15 PM" src="https://user-images.githubusercontent.com/1226677/104678216-ccc23300-569f-11eb-8bf5-c2a6e3bbc2e3.png">

**Comment by manikandanraji** [comment] 2021-01-15 03:39
you need to start the backend dev server. Did you do that?

**Comment by bigbadbrad** [comment] 2021-01-15 04:00
yes - a few errors - They don't seem to be serious ones.

<img width="868" alt="Screen Shot 2021-01-14 at 7 57 44 PM" src="https://user-images.githubusercontent.com/1226677/104679705-2415d280-56a3-11eb-8a93-ac9200c3dd23.png">

**Comment by manikandanraji** [comment] 2021-01-15 04:16
are you running the database locally or using a cloud provider like heroku, elephantsql?

**Comment by bigbadbrad** [comment] 2021-01-15 04:18
locally currently - see attached.  Is it easier to configure using heroku?

<img width="942" alt="Screen Shot 2021-01-14 at 8 17 25 PM" src="https://user-images.githubusercontent.com/1226677/104680829-a69f9180-56a5-11eb-8e40-ea2171683646.png">

**Comment by manikandanraji** [comment] 2021-01-15 04:38
when you are running your db locally, you need to disable ssl connection. Open your src/sequelize.js file in the backend repo and make the following changes

![carbon (1)](https://user-images.githubusercontent.com/34580944/104681877-6974e700-5719-11eb-94f5-57cc6f915f6e.png)

**Comment by bigbadbrad** [comment] 2021-01-15 04:56
Hi that seems to have helped - the tables are being generated.
But now when I create a new user, it doesn't tell me it was created.  But if I try it again, then it says the username is already taken.  And if I try to login using that username, it doesn't work.

<img width="957" alt="Screen Shot 2021-01-14 at 8 54 37 PM" src="https://user-images.githubusercontent.com/1226677/104683049-fd5b9a00-56aa-11eb-82d3-50022e49e7ef.png">
<img width="1440" alt="Screen Shot 2021-01-14 at 8 53 29 PM" src="https://user-images.githubusercontent.com/1226677/104683059-00ef2100-56ab-11eb-8335-ad82899e82bc.png">

**Comment by manikandanraji** [comment] 2021-01-15 04:59
you need login using the email and password combination.

**Comment by bigbadbrad** [comment] 2021-01-15 05:05
When I try to sign up, it doesn't say in upper-right that an account was created.

And when I try to login using email/password, then nothing happens.

<img width="1404" alt="Screen Shot 2021-01-14 at 9 03 57 PM" src="https://user-images.githubusercontent.com/1226677/104683598-17e24300-56ac-11eb-8249-3dbb04ac4f5f.png">

**Comment by manikandanraji** [comment] 2021-01-15 05:08
can you clone the latest version of the frontend repo and try again?

**Comment by bigbadbrad** [comment] 2021-01-15 05:18
New clone.  Now I get this.

<img width="1440" alt="Screen Shot 2021-01-14 at 9 17 29 PM" src="https://user-images.githubusercontent.com/1226677/104684502-0863f980-56ae-11eb-853b-843301464d87.png">
<img width="1440" alt="Screen Shot 2021-01-14 at 9 16 43 PM" src="https://user-images.githubusercontent.com/1226677/104684510-0bf78080-56ae-11eb-98a5-f41960c443f3.png">
<img width="1401" alt="Screen Shot 2021-01-14 at 9 16 05 PM" src="https://user-images.githubusercontent.com/1226677/104684512-0c901700-56ae-11eb-81a1-c3242ba9a833.png">

**Comment by manikandanraji** [comment] 2021-01-15 05:24
In your backend repo, remove the comment 

change this:
JWT_EXPIRE=30d // or any reasonable value that you prefer

to this:
JWT_EXPIRE=30d

**Comment by bigbadbrad** [comment] 2021-01-15 05:25
I think I'm in - JWT_EXPIRE needed to be fixed.  thx!
<img width="1407" alt="Screen Shot 2021-01-14 at 9 23 24 PM" src="https://user-images.githubusercontent.com/1226677/104685022-03ec1080-56af-11eb-8052-923dbd644cc4.png">


<img width="771" alt="Screen Shot 2021-01-14 at 9 23 36 PM" src="https://user-images.githubusercontent.com/1226677/104684940-e159f780-56ae-11eb-9591-da7cd5c70013.png">

**Comment by manikandanraji** [comment] 2021-01-15 05:32
If you try to post any videos and encounter any error, make sure you setup upload preset. If you want more instructions, refer this [https://github.com/manikandanraji/youtubeclone-frontend/wiki](url)

**Comment by bigbadbrad** [comment] 2021-01-15 06:18
Yes, I do have issues with upload.  I updated preset on cloudinary.  But issues w/ UUID
<img width="1423" alt="Screen Shot 2021-01-14 at 10 17 07 PM" src="https://user-images.githubusercontent.com/1226677/104688872-65fc4400-56b6-11eb-8126-32479bbd4b0c.png">
<img width="1440" alt="Screen Shot 2021-01-14 at 10 15 31 PM" src="https://user-images.githubusercontent.com/1226677/104688877-698fcb00-56b6-11eb-9d33-b12eb918b6c4.png">

**Comment by bigbadbrad** [comment] 2021-01-15 06:19
<img width="1440" alt="Screen Shot 2021-01-14 at 10 15 21 PM" src="https://user-images.githubusercontent.com/1226677/104688951-8cba7a80-56b6-11eb-8c19-d7b4ce362530.png">

**Comment by manikandanraji** [comment] 2021-01-15 06:21
you need to set the upload preset name to 'youtubeclone' in cloudinary.

**Comment by bigbadbrad** [comment] 2021-01-15 06:44
Everything now appears to be working.  Thank you!  I sent you an email yesterday - did you receive it?  I need help and can hire to add features to this - mainly bitcoin.

<img width="1430" alt="Screen Shot 2021-01-14 at 10 40 59 PM" src="https://user-images.githubusercontent.com/1226677/104690748-d8225800-56b9-11eb-8570-1649ea47838c.png">

**Comment by manikandanraji** [comment] 2021-01-15 12:44
I am not familiar with bitcoin. So I am not qualified for your usecase.  If your issue  got resolved, I urge to close this. Cheers

**Closed** 2021-01-15 20:14 UTC
